modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="tr_slender"
version="0.9.00"
displayName="The Rise of Slender"
credits="Mod made by Voxla - Created using mod maker MCreator"
displayURL="https://www.curseforge.com/members/voxla/projects"
logoFile="logo.png"
authors="Voxla"
description="A mod that tries to bring Slender: The Eight Pages into Minecraft."

[[dependencies.tr_slender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




